# Предложения

###

## Предложение по идентификатору

GET http://localhost:31337/offers/63d19988b2939be513235739 HTTP/1.1

###

## Список предложений

GET http://localhost:31337/offers HTTP/1.1

###

## Создание предложения

POST http://localhost:31337/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Тест Тест Тест",
  "description": "Тест Тест Тест Тест Тест Тест Тест Тест Тест",
  "postDate": "2023-01-23T19:06:57.484Z",
  "city": "Amsterdam",
  "previewImagePath": "preview-image4.jpg",
  "detailImagePath": [
    "detail-image6.jpg", 
    "detail-image7.jpg", 
    "detail-image8.jpg", 
    "detail-image9.jpg", 
    "detail-image10.jpg"
    ],
  "premium": true,
  "ratingCount": 1,
  "overallRating": 5,
  "averageRating": 5,
  "housingType": "room",
  "roomsNumber": 3,
  "guestsNuber": 5,
  "rentPrice": 50000,
  "amenities": ["Laptop friendly workspace", "Laptop friendly workspace", "Baby seat", "Washer", "Towels", "Fridge"],
  "commentsCount": 0,
  "coordinates":{
        "latitude": "52.370216",
        "longitude": "4.895168"
  },
  "userId": "63d19988b2939be513235724"
}

###

## Список комментариев к предложению

GET http://localhost:31337/offers/63d75b38f9cb7c774aab25dc/comments HTTP/1.1

###

## Удаление предложения

DELETE http://localhost:31337/offers/63d19988b2939be513235730 HTTP/1.1

###

## Обновление предложения

PATCH http://localhost:31337/offers/63d19988b2939be513235739 HTTP/1.1
Content-Type: application/json

{
  "description": "Новое описание новое описание новое описание новое описание",
    "title": "Тест Тест Тест",
  "postDate": "2023-01-23T19:06:57.484Z",
  "city": "Amsterdam",
  "previewImagePath": "preview-image4.jpg",
  "detailImagePath": [
    "detail-image6.jpg", 
    "detail-image7.jpg", 
    "detail-image8.jpg", 
    "detail-image9.jpg", 
    "detail-image10.jpg"
    ],
  "premium": true,
  "ratingCount": 1,
  "overallRating": 5,
  "averageRating": 5,
  "housingType": "room",
  "roomsNumber": 3,
  "guestsNuber": 5,
  "rentPrice": 50000,
  "amenities": ["Laptop friendly workspace", "Laptop friendly workspace", "Baby seat", "Washer", "Towels", "Fridge"],
  "commentsCount": 0,
  "coordinates":{
        "latitude": "52.370216",
        "longitude": "4.895168"
  }
}

###
