# Предложения

###

## Предложение по идентификатору

GET http://localhost:31337/offers/63e00dca6ac7a22e40ad4d79 HTTP/1.1

###

## Список предложений

GET http://localhost:31337/offers HTTP/1.1

###

## Создание предложения

POST http://localhost:31337/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYzZTBiNWM5ZGI0ODFmNjU5MGY1YTlhNCIsImlhdCI6MTY3NTg0NDI0OCwiZXhwIjoxNjc2MDE3MDQ4fQ.v6akmcoEd9w2o2tL8mp3R0OpTtenCUJBrMvHoog2sGM

{
  "title": "Тест Тест Тест",
  "description": "Тест Тест Тест Тест Тест Тест Тест Тест Тест",
  "postDate": "2023-01-23T19:06:57.484Z",
  "city": "Cologne",
  "previewImagePath": "preview-image.jpg",
  "detailImagePath": [
    "detail-image.jpg", 
    "detail-image1.jpg", 
    "detail-image2.jpg", 
    "detail-image3.jpg", 
    "detail-image4.jpg",
    "detail-image5.jpg"
    ],
  "premium": true,
  "ratingCount": 1,
  "overallRating": 5,
  "averageRating": 5,
  "housingType": "Room",
  "roomsNumber": 3,
  "guestsNuber": 5,
  "rentPrice": 50000,
  "amenities": ["Laptop friendly workspace", "Laptop friendly workspace", "Baby seat", "Washer", "Towels", "Fridge"],
  "commentsCount": 0,
  "coordinates":{
        "latitude": "50.938361",
        "longitude": "6.959974"
  },
  "userId": "63d19988b2939be513235724"
}

###

## Список комментариев к предложению

GET http://localhost:31337/offers/63e35aa326d2ae3475584338/comments HTTP/1.1

###

## Загрузка превью-изображения для предложения
POST http://localhost:31337/offers/63e35aa326d2ae3475584338/preview HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYzZTBiNWM5ZGI0ODFmNjU5MGY1YTlhNCIsImlhdCI6MTY3NTg0NDE2NiwiZXhwIjoxNjc2MDE2OTY2fQ.RZviN8WBdXkKm527Ww9feYe1cDIJUJk6p4hqFWOsD2k

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="preview-image.jpg"
Content-Type: image/png

< /tmp/screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Загрузка детальных изображений для предложения
POST http://localhost:31337/offers/63e35aa326d2ae3475584338/detail HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJpZCI6IjYzZTBiNWM5ZGI0ODFmNjU5MGY1YTlhNCIsImlhdCI6MTY3NTg0NDE2NiwiZXhwIjoxNjc2MDE2OTY2fQ.RZviN8WBdXkKm527Ww9feYe1cDIJUJk6p4hqFWOsD2k

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="detail-image.jpg"
Content-Type: image/png

< /tmp/screen.png

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image1"; filename="detail-image1.jpg"
Content-Type: image/png

< /tmp/screen.png

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image2"; filename="detail-image2.jpg"
Content-Type: image/png

< /tmp/screen.png

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image3"; filename="detail-image3.jpg"
Content-Type: image/png

< /tmp/screen.png

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image4"; filename="detail-image4.jpg"
Content-Type: image/png

< /tmp/screen.png

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image5"; filename="detail-image5.jpg"
Content-Type: image/png

< /tmp/screen.png

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Удаление предложения

DELETE http://localhost:31337/offers/63d19988b2939be513235730 HTTP/1.1

###

## Обновление предложения

PATCH http://localhost:31337/offers/63d19988b2939be513235739 HTTP/1.1
Content-Type: application/json

{
  "description": "Новое описание новое описание новое описание новое описание",
    "title": "Тест Тест Тест",
  "postDate": "2023-01-23T19:06:57.484Z",
  "city": "Amsterdam",
  "previewImagePath": "preview-image4.jpg",
  "detailImagePath": [
    "detail-image6.jpg", 
    "detail-image7.jpg", 
    "detail-image8.jpg", 
    "detail-image9.jpg", 
    "detail-image10.jpg"
    ],
  "premium": true,
  "ratingCount": 1,
  "overallRating": 5,
  "averageRating": 5,
  "housingType": "room",
  "roomsNumber": 3,
  "guestsNuber": 5,
  "rentPrice": 50000,
  "amenities": ["Laptop friendly workspace", "Laptop friendly workspace", "Baby seat", "Washer", "Towels", "Fridge"],
  "commentsCount": 0,
  "coordinates":{
        "latitude": "52.370216",
        "longitude": "4.895168"
  }
}

###

## Новые предложения

GET http://localhost:31337/offers/bundles/new HTTP/1.1

###

## Обсуждаемые предложения

GET http://localhost:31337/offers/bundles/discussed HTTP/1.1

###