export enum ValidateConstants {
  MinNameLength = 1,
  MaxNameLength = 15,
  MinPasswordLength = 6,
  MaxPasswordLength = 12,
  MinLengthTitle = 10,
  MaxLengthTitle = 100,
  MinOfferDescriptionLength = 20,
  MaxOfferDescriptionLength = 1024,
  MaxLengthImage = 256,
  MinCountDetailImages = 6,
  MaxCountDetailImages = 6,
  MaxDecimalPlaces = 1,
  MinAverageRating = 1,
  MaxAverageRating = 5,
  MinRoomsNumber = 1,
  MaxRoomsNumber = 8,
  MinGuestsNumber = 1,
  MaxGuestsNumber = 10,
  MinRentPrice = 100,
  MaxRentPrice = 100000,
  MinCommentLength = 5,
  MaxCommentLength = 1024,
}
