export enum ValidateConstants {
  minNameLength = 1,
  maxNameLength = 15,
  minPasswordLength = 6,
  maxPasswordLength = 12,
  minLengthTitle = 10,
  maxLengthTitle = 100,
  minOfferDescriptionLength = 20,
  maxOfferDescriptionLength = 1024,
  maxLengthImage = 256,
  minCountDetailImages = 6,
  maxCountDetailImages = 6,
  maxDecimalPlaces = 1,
  minAverageRating = 1,
  maxAverageRating = 5,
  minRoomsNumber = 1,
  maxRoomsNumber = 8,
  minGuestsNumber = 1,
  maxGuestsNumber = 10,
  minRentPrice = 100,
  maxRentPrice = 100000,
  minCommentLength = 5,
  maxCommentLength = 1024,
}
