export enum ValidateConstants {
  MinNameLength = 1,
  MaxNameLength = 15,
  MinPasswordLength = 6,
  MaxPasswordLength = 12,
  MinLengthTitle = 10,
  MaxLengthTitle = 100,
  MinOfferDescriptionLength = 20,
  MaxOfferDescriptionLength = 1024,
  MaxLengthImage = 256,
  MinCountDetailImages = 6,
  MaxCountDetailImages = 6,
  maxDecimalPlaces = 1,
  minAverageRating = 1,
  maxAverageRating = 5,
  minRoomsNumber = 1,
  maxRoomsNumber = 8,
  minGuestsNumber = 1,
  maxGuestsNumber = 10,
  minRentPrice = 100,
  maxRentPrice = 100000,
  minCommentLength = 5,
  maxCommentLength = 1024,
}
